import { useEffect, useState } from 'react'
import { Download, FileBarChart } from 'lucide-react'
import { api } from '../api/client'
import type { ReportFilter, ReportOptions, ReportResult } from '../api/types'

const currentYear = new Date().getFullYear()

export function ReportsPage() {
  const [options, setOptions] = useState<ReportOptions>(); const [key, setKey] = useState('patient-registration'); const [filter, setFilter] = useState<ReportFilter>({ dateFrom: `${currentYear}-01-01` }); const [result, setResult] = useState<ReportResult>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { api.reportOptions().then(setOptions).catch(e => setError(e.message)) }, [])
  const run = async () => { if (filter.dateFrom && filter.dateTo && filter.dateFrom > filter.dateTo) return setError('End date must be on or after start date.'); setLoading(true); setError(''); try { setResult(await api.report(key, filter)) } catch (e) { setError(e instanceof Error ? e.message : 'Report failed.') } finally { setLoading(false) } }
  const pdf = async () => { const file = await api.reportPdf(key, filter); const url = URL.createObjectURL(file.blob); const link = document.createElement('a'); link.href = url; link.download = file.fileName; link.click(); URL.revokeObjectURL(url) }
  return <><header className="page-header"><div><p className="eyebrow">Operational intelligence</p><h1>Reports</h1><p>Review all clinical and registration report families using consistent filters.</p></div><button className="button secondary" disabled={!result} onClick={() => void pdf()}><Download size={17} /> Export PDF</button></header><section className="panel report-filter"><label><span>Report</span><select value={key} onChange={e => setKey(e.target.value)}>{options?.reports.map(x => <option key={x.key} value={x.key}>{x.title}</option>)}</select></label><label><span>From</span><input type="date" value={filter.dateFrom ?? ''} onChange={e => setFilter({ ...filter, dateFrom: e.target.value })} /></label><label><span>To</span><input type="date" value={filter.dateTo ?? ''} onChange={e => setFilter({ ...filter, dateTo: e.target.value })} /></label><label><span>Centre</span><select value={filter.centerId ?? ''} onChange={e => setFilter({ ...filter, centerId: e.target.value ? Number(e.target.value) : undefined })}><option value="">All centres</option>{options?.centers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Province</span><select value={filter.provinceId ?? ''} onChange={e => setFilter({ ...filter, provinceId: e.target.value ? Number(e.target.value) : undefined })}><option value="">All provinces</option>{options?.provinces.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Patient number</span><input value={filter.patientNumber ?? ''} onChange={e => setFilter({ ...filter, patientNumber: e.target.value })} /></label><button className="button primary" disabled={loading} onClick={() => void run()}>{loading ? 'Running…' : 'Run report'}</button></section>{error && <div className="error-panel"><strong>Report unavailable</strong><span>{error}</span></div>}<section className="panel report-result"><div className="panel-heading"><div><h2>{result?.title ?? 'Report results'}</h2><p>{result ? `${result.totalCount} rows` : 'Choose filters and run the report.'}</p></div><FileBarChart size={20} /></div>{result && <div className="table-wrap"><table><thead><tr>{result.headers.map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{result.rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j} data-label={result.headers[j]}>{cell || '—'}</td>)}</tr>)}</tbody></table></div>}</section></>
}
