[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.build]
cmds = [
  'dotnet restore POMS/POMS.sln',
  'dotnet build POMS/POMS.sln -c Release --no-restore'
]

[phases.deploy]
cmds = ['cd POMS/src/Poms.Web && dotnet Poms.Web.dll']

[start]
cmd = 'cd POMS/src/Poms.Web && dotnet Poms.Web.dll'
