import { Download, FileText, ShieldAlert, Trash2, Upload } from 'lucide-react'
import { useRef, useState, type FormEvent } from 'react'
import { api, ApiError } from '../api/client'
import type { StoredDocument } from '../api/types'
import { EmptyState, ErrorPanel, LoadingRows } from './Ui'
import { useApi } from '../hooks/useApi'

export function DocumentPanel({ scope, ownerId }: { scope: 'patient' | 'episode'; ownerId: string }) {
  const [refreshKey, setRefreshKey] = useState(0)
  const documents = useApi(() => api.documents(scope, ownerId), `documents-${scope}-${ownerId}-${refreshKey}`)
  const options = useApi(() => api.documentOptions(), 'document-options')
  const [type, setType] = useState('Other'); const [notes, setNotes] = useState(''); const [restricted, setRestricted] = useState(false); const [file, setFile] = useState<File>(); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const fileInput = useRef<HTMLInputElement>(null)
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!file || submitting) return; setSubmitting(true); setError(''); try { await api.uploadDocument(scope, ownerId, type, notes, restricted, file); setNotes(''); setRestricted(false); setFile(undefined); if (fileInput.current) fileInput.current.value = ''; setRefreshKey((value) => value + 1) } catch (failure) { setError(failure instanceof ApiError ? failure.message : 'The document could not be uploaded.') } finally { setSubmitting(false) } }
  const download = async (item: StoredDocument) => { setError(''); try { const result = await api.downloadDocument(item); const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = result.fileName; link.click(); URL.revokeObjectURL(url) } catch (failure) { setError(failure instanceof Error ? failure.message : 'The document could not be downloaded.') } }
  const remove = async (item: StoredDocument) => { if (!window.confirm(`Delete ${item.fileName}?`)) return; setError(''); try { await api.deleteDocument(item); setRefreshKey((value) => value + 1) } catch (failure) { setError(failure instanceof Error ? failure.message : 'The document could not be deleted.') } }
  return <section className="panel document-panel"><header className="section-heading"><div><p className="eyebrow">Secure files</p><h2>Documents</h2></div></header><form className="document-upload" onSubmit={(event) => void submit(event)}>{error && <div className="inline-error wide">{error}</div>}<label className="form-field"><span>Document type *</span><select value={type} onChange={(event) => setType(event.target.value)}>{options.data?.documentTypes.map((value) => <option key={value}>{value.replace(/([a-z])([A-Z])/g, '$1 $2')}</option>)}</select></label><label className="form-field"><span>File *</span><input ref={fileInput} required type="file" accept={options.data?.allowedExtensions.join(',')} onChange={(event) => setFile(event.target.files?.[0])} /><small>Maximum {options.data?.maxFileSizeMb ?? 10} MB</small></label><label className="form-field"><span>Notes</span><input value={notes} maxLength={1000} onChange={(event) => setNotes(event.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={restricted} onChange={(event) => setRestricted(event.target.checked)} /><span><strong>Restricted</strong><small>Limit access to authorized users.</small></span></label><button className="button primary" disabled={!file || submitting} type="submit"><Upload size={16} /> {submitting ? 'Uploading…' : 'Upload'}</button></form>{documents.error ? <ErrorPanel message={documents.error} retry={documents.refresh} /> : documents.loading ? <LoadingRows /> : !documents.data?.length ? <EmptyState><FileText size={30} /><h2>No documents</h2><p>Upload supporting records when needed.</p></EmptyState> : <div className="document-list">{documents.data.map((item) => <article key={item.id}><FileText size={20} /><div><strong>{item.fileName}</strong><span>{item.documentType.replace(/([a-z])([A-Z])/g, '$1 $2')} · {new Date(item.uploadedAt).toLocaleString('en-GB')}</span>{item.notes && <small>{item.notes}</small>}</div>{item.isRestricted && <ShieldAlert className="restricted-icon" size={16} />}<button type="button" className="icon-button" onClick={() => void download(item)} aria-label={`Download ${item.fileName}`}><Download /></button><button type="button" className="icon-button danger" onClick={() => void remove(item)} aria-label={`Delete ${item.fileName}`}><Trash2 /></button></article>)}</div>}</section>
}
